# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:
  
env:

  NEXUS_URL: ${{ secrets.NEXUS_URL }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  //MAVEN_REPO_PATH: ${{ secrets.MAVEN_REPO_PATH || 'repository/maven-releases' }}

  
jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

      #  Deploy to appropriate Nexus repository
      - name: Deploy main JAR only to Nexus
        run: |
          JAR_FILE=$(find target -type f -name "*.jar"| head -n 1)
          echo "Found JAR: $JAR_FILE"
      
          mvn deploy:deploy-file \
            -Dfile="$JAR_FILE" \
            -DgroupId=com.example \
            -DartifactId=your-app \
            -Dversion=1.0.0 \
            -Dpackaging=jar \
            -DrepositoryId=nexus \
            -Durl=http://192.168.178.94:8082/repository/Calc-maven-hosted-repo/ \
            -DgeneratePom=true
